export const PREDEFINED_ITEMS = [
  "Lemon Chilli",
  "Tomato Muchies",
  "Creamy Onion",
  "Salt Punch",
  "Cristos Mexican Chilli",
  "Masala Bite",
  "Cristos African Mint",
  "Cristos Salted",
  "Korean BB Q",
  "Tomato Cups",
  "Sticks",
  "Plane",
  "Alphabet",
  "Jeera Papad",
  "Channa Dal",
  "Moong Dal",
  "Masala Singh",
  "Tasty Peanuts",
  "Salted Peanuts",
  "Punjabi Tadka",
  "Thikha Mitha",
  "Kolhapuri Bhadang",
  "Sabudana Chivda",
  "Sev Murmura",
  "Masala Sev Murmura",
  "Thikha Mitha Mix",
  "Sev",
  "Aloo Bhujia Sev",
  "Bhavanagiri Ghatiya",
  "Soya Sticks",
  "Nutches Cheesy",
  "Thai Chilli",
];
