// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dmzpqthoegypueywmuxy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRtenBxdGhvZWd5cHVleXdtdXh5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyODQyMzMsImV4cCI6MjA2ODg2MDIzM30.h0_kI0fmmtzPn4zgaw3d8UwOXK0XuzKCPDdLiibLi5M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});